In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/refs/heads/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Data Cleaning

In [4]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(int(df['test_score(out of 10)'].mean()))
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=84138aebc2ba99c5f11d49e56c2649995f5ec1f169df51d73b93e3ef3a3178ef
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [6]:
from word2number import w2n
def convert_experience(x):
  try:
    return w2n.word_to_num(x)
  except:
    return None
df['experience']=df['experience'].apply(convert_experience)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [7]:
df['experience']=df['experience'].fillna(0)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0                    8.0                           9      50000
1         0.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    7.0                           7      72000
7        11.0                    7.0                           8      80000

In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])
reg.coef_,reg.intercept_

(array([2922.26901502, 2221.30909959, 2147.48256637]),
 np.float64(14992.65144669314))

In [9]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [10]:
reg.predict([[12,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([93747.79628651])

In [11]:
import joblib

In [12]:
joblib.dump(reg,'Salary_Prediction_Model')

['Salary_Prediction_Model']

In [13]:
Salary_Prediction_Model=joblib.load('Salary_Prediction_Model')

In [15]:
Salary_Prediction_Model.predict([[50,7,8]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([193835.12642581])